/**
 * GENERATED by scripts/build-audit-galleries.mjs — do not hand-edit.
 *
 * kind: "mixed"  screens from the SCBX artefact, carrying its own descriptions
 *       "store"  official App Store screenshots — marketing creatives chosen by
 *                the vendor, showing how a product presents itself rather than
 *                how it behaves
 */

export interface GalleryScreen {
  src: string;
  caption: string;
  archetype: string;
}

export interface Gallery {
  name: string;
  seller?: string;
  source: string;
  storeUrl?: string;
  icon?: string;
  kind: 'mixed' | 'store';
  rating?: number;
  ratingCount?: number;
  screens: GalleryScreen[];
}

export const galleries: Record<string, Gallery> = {
  "scb-easy": {
    "name": "SCB EASY",
    "seller": "The Siam Commercial Bank PCL",
    "source": "SCBX Screen Estate artefact",
    "storeUrl": "https://apps.apple.com/th/app/scb-easy/id568388474?uo=4",
    "icon": "/audit/scb-easy/icon.png",
    "kind": "mixed",
    "rating": 3.4,
    "ratingCount": 25502,
    "screens": [
      {
        "src": "/screens/scb-easy-01.jpg",
        "caption": "Store creative of the home shortcut grid — Scan / My QR bar, tiles for family transfers, mobile top-up, transactions, Easy Pass and bills, then a promo carousel and a COVID-19 relief card.",
        "archetype": "Home"
      },
      {
        "src": "/screens/scb-easy-02.jpg",
        "caption": "Same home creative, taller crop — also shows the five-item bottom bar and an Apply Loan & Credit Card row.",
        "archetype": "Home"
      },
      {
        "src": "/screens/scb-easy-03.jpg",
        "caption": "Home dashboard: photo header, greeting, Scan / My QR bar, six service tiles, theme-store promotion, Easy Store strip, loan CTA, icon-only bottom bar",
        "archetype": "Home"
      },
      {
        "src": "/screens/scb-easy-04.jpg",
        "caption": "Just4U spending insight — savings and credit-card tabs, a donut of April spend 32,655.45 with category breakdown and a View monthly spending button.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-05.jpg",
        "caption": "Just4U spending insight — savings and credit-card tabs, a donut of April spend 32,655.45 with category breakdown and a View monthly spending button.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-06.jpg",
        "caption": "Account summary — deposits and shops, each section a one-card carousel with a pager dot",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-07.jpg",
        "caption": "Account summary scrolled — cards, revolving loans and insurances",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-08.jpg",
        "caption": "My deposits — balance right-aligned and unlabelled, More services dropdown pill",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-09.jpg",
        "caption": "My deposits — account details expanded",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-10.jpg",
        "caption": "Transaction history — uncategorised rows, free-text notes",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-11.jpg",
        "caption": "Transaction period filter",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-12.jpg",
        "caption": "Credit card details",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/scb-easy-13.jpg",
        "caption": "Personalised home with a quick-action grid (Transfer highlighted) over a wall of biller and partner logos.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-14.jpg",
        "caption": "Personalised home with a quick-action grid (Transfer highlighted) over a wall of biller and partner logos.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-15.jpg",
        "caption": "Cardless ATM withdrawal — account and card tabs, amount chips, a 100–30,000 range field with daily-limit helper text and a primary Verify details button.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-16.jpg",
        "caption": "Cardless ATM withdrawal — account and card tabs, amount chips, a 100–30,000 range field with daily-limit helper text and a primary Verify details button.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-17.jpg",
        "caption": "Transfer — 11 favourites as identical letter avatars, source account carousel, 16 banks as coloured initial tokens",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-18.jpg",
        "caption": "Transfer — destination bank picker",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-19.jpg",
        "caption": "Transfer — PromptPay tab",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-20.jpg",
        "caption": "Transfer — history tab",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-21.jpg",
        "caption": "Transfer form — recipient and amount",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-22.jpg",
        "caption": "Transfer form — amount entry keypad",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-23.jpg",
        "caption": "Transfer form — complete, ready to review",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-24.jpg",
        "caption": "Set a schedule — once",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/scb-easy-25.jpg",
        "caption": "Open a deposit account without a branch — NDID, 7-Eleven and Boonterm verification logos over a 3×4 service grid with the open-account tile lifted.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/scb-easy-26.jpg",
        "caption": "Open a deposit account without a branch — NDID, 7-Eleven and Boonterm verification logos over a 3×4 service grid with the open-account tile lifted.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/scb-easy-27.jpg",
        "caption": "Apply for loans and credit cards — a two-column catalogue of Up lending, Speedy Loan, Speedy Cash and Credit card.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/scb-easy-28.jpg",
        "caption": "Apply for loans and credit cards — a two-column catalogue of Up lending, Speedy Loan, Speedy Cash and Credit card.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/scb-easy-29.jpg",
        "caption": "Banking services — 15-cell grid, one cell disabled, no search",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-30.jpg",
        "caption": "My deposits — more services bottom sheet",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-31.jpg",
        "caption": "Service centre — six quick actions in a floating card over a dimmed home",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-32.jpg",
        "caption": "All services — three tabs, two-column lists, the only search in the app",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-33.jpg",
        "caption": "Notification list",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-34.jpg",
        "caption": "More options menu",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-35.jpg",
        "caption": "Calendar — scheduled transactions",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-36.jpg",
        "caption": "Settings",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/scb-easy-37.jpg",
        "caption": "Easy Bonus — coupon-code input, a received-bonus carousel (Starbucks × SCB Debit Mastercard) and an activities section.",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/scb-easy-38.jpg",
        "caption": "Credit card points — 377 points, every action opens PointX",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/scb-easy-39.jpg",
        "caption": "Gift box — received",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/scb-easy-40.jpg",
        "caption": "Review transfer — red icon and red body copy where a summary belongs",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/scb-easy-41.jpg",
        "caption": "PIN authorisation",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/scb-easy-42.jpg",
        "caption": "Transfer successful — slip with watermark, four forward actions",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/scb-easy-43.jpg",
        "caption": "Transfer slip — QR and actions",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/scb-easy-44.jpg",
        "caption": "PIN entry with biometric prompt",
        "archetype": "Login & onboarding"
      },
      {
        "src": "/screens/scb-easy-45.jpg",
        "caption": "Partner app handoff interstitial — full screen, one button, no cancel",
        "archetype": "Cross-app handoff"
      },
      {
        "src": "/screens/scb-easy-46.jpg",
        "caption": "Lock-screen push notification for a ฿300.00 credit. No app UI.",
        "archetype": "Marketing"
      }
    ]
  },
  "cardx": {
    "name": "CardX",
    "seller": "CARD X COMPANY LIMITED",
    "source": "SCBX Screen Estate artefact",
    "storeUrl": "https://apps.apple.com/th/app/cardx/id1622961294?uo=4",
    "icon": "/audit/cardx/icon.png",
    "kind": "mixed",
    "rating": 2.55,
    "ratingCount": 1846,
    "screens": [
      {
        "src": "/screens/cardx-01.jpg",
        "caption": "Card home: carousel of CardX VISA ····5789 with POINTX 531 and available credit 145,100.25, quick actions for instalment conversion, split payment and statement request, an application-status tile and an offers card.",
        "archetype": "Home"
      },
      {
        "src": "/screens/cardx-02.jpg",
        "caption": "Card home: carousel of CardX VISA ····5789 with POINTX 531 and available credit 145,100.25, quick actions for instalment conversion, split payment and statement request, an application-status tile and an offers card.",
        "archetype": "Home"
      },
      {
        "src": "/screens/cardx-03.jpg",
        "caption": "Home screen right edge: balance tile, pay-card and application-status shortcuts, a personalised offer card and a promotions carousel.",
        "archetype": "Home"
      },
      {
        "src": "/screens/cardx-04.jpg",
        "caption": "Instalment conversion — a checkbox list of eligible purchases (Fuji ฿2,000 and ZARA ฿2,500 selected), running total ฿4,500 and a Next button.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/cardx-05.jpg",
        "caption": "Instalment conversion — a checkbox list of eligible purchases (Fuji ฿2,000 and ZARA ฿2,500 selected), running total ฿4,500 and a Next button.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/cardx-06.jpg",
        "caption": "Cash advance (\"ดีจัง\") — account chip strip, a 25% p.a. rate warning, amount chips with 15,000 selected, and a repayment-plan radio group.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/cardx-07.jpg",
        "caption": "CardX ULTRA PLATINUM product page — card art, minimum income ฿15,000/month, a calculate-limit row and an Apply now CTA.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/cardx-08.jpg",
        "caption": "CardX ULTRA PLATINUM product page — card art, minimum income ฿15,000/month, a calculate-limit row and an Apply now CTA.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/cardx-09.jpg",
        "caption": "Permanent credit-limit increase — income-type dropdown, monthly income field, calculate-limit button and a stepper across a 15,000–50,000 range.",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/cardx-10.jpg",
        "caption": "Permanent credit-limit increase — income-type dropdown, monthly income field, calculate-limit button and a stepper across a 15,000–50,000 range.",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/cardx-11.jpg",
        "caption": "Card controls for CardX BEYOND — credit-limit stepper at ฿150,000 across a 10,000–200,000 range, with a modal sheet for a daily spend cap and a Confirm button.",
        "archetype": "Services & support"
      },
      {
        "src": "/screens/cardx-12.jpg",
        "caption": "Promotion detail — Swensen's e-discount coupon up to ฿80, eligibility for CardX and SCB cards, terms and a Register CTA.",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/cardx-13.jpg",
        "caption": "Promotion detail — Swensen's e-discount coupon up to ฿80, eligibility for CardX and SCB cards, terms and a Register CTA.",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/cardx-14.jpg",
        "caption": "Brand cover — CardX wordmark and Thai positioning as a core SCBX business. Only slivers of a home feed visible.",
        "archetype": "Marketing"
      }
    ]
  },
  "invx": {
    "name": "INVX",
    "seller": "InnovestX Securities Co., Ltd.",
    "source": "SCBX Screen Estate artefact",
    "storeUrl": "https://apps.apple.com/th/app/invx-innovestx-%E0%B9%81%E0%B8%AD%E0%B8%9B%E0%B8%81%E0%B8%B2%E0%B8%A3%E0%B8%A5%E0%B8%87%E0%B8%97-%E0%B8%99/id1434520713?uo=4",
    "icon": "/audit/invx/icon.png",
    "kind": "mixed",
    "rating": 3.97,
    "ratingCount": 5112,
    "screens": [
      {
        "src": "/screens/invx-01.jpg",
        "caption": "INVX dark home — avatar with PLATINUM tier chip, a points promo card, a purple portfolio card showing ฿1,789,487,320 and +1.24%, a price-change row and a deposit nudge.",
        "archetype": "Home"
      },
      {
        "src": "/screens/invx-02.jpg",
        "caption": "INVX dark home — avatar with PLATINUM tier chip, a points promo card, a purple portfolio card showing ฿1,789,487,320 and +1.24%, a price-change row and a deposit nudge.",
        "archetype": "Home"
      },
      {
        "src": "/screens/invx-03.jpg",
        "caption": "Port Analytics — asset breakdown donut with a weight / P&L toggle and rows for bonds, stocks, structured notes, cash, intelligent port, digital assets and funds.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/invx-04.jpg",
        "caption": "Port Analytics — asset breakdown donut with a weight / P&L toggle and rows for bonds, stocks, structured notes, cash, intelligent port, digital assets and funds.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/invx-05.jpg",
        "caption": "Trade — symbol search and price alert, asset-class tabs, recently viewed tiles, INVX Picks chips and a watchlist top-gainer card.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/invx-06.jpg",
        "caption": "Trade — symbol search and price alert, asset-class tabs, recently viewed tiles, INVX Picks chips and a watchlist top-gainer card.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/invx-07.jpg",
        "caption": "Discover — Opportunities / Markets & News segmented control, INVX Picks with asset-class filter chips, SCB and AOT cards each with an upside figure and a \"Why?\" chip, then a trending chip cloud.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/invx-08.jpg",
        "caption": "Discover — Opportunities / Markets & News segmented control, INVX Picks with asset-class filter chips, SCB and AOT cards each with an upside figure and a \"Why?\" chip, then a trending chip cloud.",
        "archetype": "Products & apply"
      },
      {
        "src": "/screens/invx-09.jpg",
        "caption": "Instrument detail for AMD — price and day range, volume and market cap, an INVX fundamental radar chart, and a green Buy / red Sell bar.",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/invx-10.jpg",
        "caption": "Instrument detail for AMD — price and day range, volume and market cap, an INVX fundamental radar chart, and a green Buy / red Sell bar.",
        "archetype": "Detail & confirmation"
      },
      {
        "src": "/screens/invx-11.jpg",
        "caption": "Brand plate — innovestX logo, \"Your Future, Empowered\", 3D coin render. The phone edge is too clipped to read.",
        "archetype": "Marketing"
      },
      {
        "src": "/screens/invx-12.jpg",
        "caption": "Brand plate — innovestX logo, \"Your Future, Empowered\", 3D coin render. The phone edge is too clipped to read.",
        "archetype": "Marketing"
      }
    ]
  },
  "pointx": {
    "name": "POINTX",
    "seller": "SCB TECH X COMPANY LIMITED",
    "source": "SCBX Screen Estate artefact",
    "storeUrl": "https://apps.apple.com/th/app/pointx-app/id1596876529?uo=4",
    "icon": "/audit/pointx/icon.png",
    "kind": "mixed",
    "rating": 4.01,
    "ratingCount": 1138,
    "screens": [
      {
        "src": "/screens/pointx-01.jpg",
        "caption": "PointX home — greeting, a 25,000 point balance chip, quick actions for partner points, cashback, airlines and coupons, a top-sellers carousel and a flash-deal rail with Baht + point pricing. Tab bar: Home / Shop / SCB EASY hub / X Store / My POINTX.",
        "archetype": "Home"
      },
      {
        "src": "/screens/pointx-02.jpg",
        "caption": "PointX home — greeting, a 25,000 point balance chip, quick actions for partner points, cashback, airlines and coupons, a top-sellers carousel and a flash-deal rail with Baht + point pricing. Tab bar: Home / Shop / SCB EASY hub / X Store / My POINTX.",
        "archetype": "Home"
      },
      {
        "src": "/screens/pointx-03.jpg",
        "caption": "PointX home — own navigation, colour and type; partner points, coupons, cashback, airlines, transfer",
        "archetype": "Home"
      },
      {
        "src": "/screens/pointx-04.jpg",
        "caption": "My POINTX — balance card with history link, linked-card strip and an all-partners list (AIS, Amaze, Bangchak, blueplus+, J Point, MAX CARD) with balances and conversion rates.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/pointx-05.jpg",
        "caption": "My POINTX — balance card with history link, linked-card strip and an all-partners list (AIS, Amaze, Bangchak, blueplus+, J Point, MAX CARD) with balances and conversion rates.",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/pointx-06.jpg",
        "caption": "PointX my points",
        "archetype": "Accounts & portfolio"
      },
      {
        "src": "/screens/pointx-07.jpg",
        "caption": "Pay with points — a phone at a POS terminal with a QR and an all-points / partial-points toggle over an amount field; beneath it the Shop tab with category chips and a special-rate grid.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/pointx-08.jpg",
        "caption": "Pay with points — a phone at a POS terminal with a QR and an all-points / partial-points toggle over an amount field; beneath it the Shop tab with category chips and a special-rate grid.",
        "archetype": "Transact & pay"
      },
      {
        "src": "/screens/pointx-09.jpg",
        "caption": "PointX X Store",
        "archetype": "Rewards & offers"
      },
      {
        "src": "/screens/pointx-10.jpg",
        "caption": "Welcome creative — POINTX wordmark, a model holding a phone showing only the splash, and 3D X-coins.",
        "archetype": "Marketing"
      },
      {
        "src": "/screens/pointx-11.jpg",
        "caption": "Welcome creative — POINTX wordmark, a model holding a phone showing only the splash, and 3D X-coins.",
        "archetype": "Marketing"
      },
      {
        "src": "/screens/pointx-12.jpg",
        "caption": "X Store rewards creative — floating reward cards for Shopee, iPhone, LINEMAN and Sony. Decorative, not legible UI.",
        "archetype": "Marketing"
      },
      {
        "src": "/screens/pointx-13.jpg",
        "caption": "X Store rewards creative — floating reward cards for Shopee, iPhone, LINEMAN and Sony. Decorative, not legible UI.",
        "archetype": "Marketing"
      }
    ]
  },
  "kbank": {
    "name": "K PLUS",
    "seller": "KASIKORNBANK PUBLIC COMPANY LIMITED",
    "source": "Apple App Store (TH)",
    "storeUrl": "https://apps.apple.com/th/app/k-plus/id361170631?uo=4",
    "icon": "/audit/kbank/icon.png",
    "kind": "store",
    "rating": 3.68,
    "ratingCount": 32807,
    "screens": [
      {
        "src": "/audit/kbank/01.jpg",
        "caption": "K PLUS — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/kbank/02.jpg",
        "caption": "K PLUS — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/kbank/03.jpg",
        "caption": "K PLUS — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/kbank/04.jpg",
        "caption": "K PLUS — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/kbank/05.jpg",
        "caption": "K PLUS — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/kbank/06.jpg",
        "caption": "K PLUS — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "truemoney": {
    "name": "TrueMoney - Pay & Earn Coins",
    "seller": "True Money Company Limited",
    "source": "Apple App Store (TH)",
    "storeUrl": "https://apps.apple.com/th/app/truemoney-pay-earn-coins/id663885752?uo=4",
    "icon": "/audit/truemoney/icon.png",
    "kind": "store",
    "rating": 3.97,
    "ratingCount": 69715,
    "screens": [
      {
        "src": "/audit/truemoney/01.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/truemoney/02.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/truemoney/03.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/truemoney/04.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/truemoney/05.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/truemoney/06.jpg",
        "caption": "TrueMoney - Pay & Earn Coins — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "dbs": {
    "name": "DBS digibank",
    "seller": "DBS Bank Ltd",
    "source": "Apple App Store (SG)",
    "storeUrl": "https://apps.apple.com/sg/app/dbs-digibank/id1068403826?uo=4",
    "icon": "/audit/dbs/icon.png",
    "kind": "store",
    "rating": 4.67,
    "ratingCount": 159054,
    "screens": [
      {
        "src": "/audit/dbs/01.jpg",
        "caption": "DBS digibank — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/dbs/02.jpg",
        "caption": "DBS digibank — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/dbs/03.jpg",
        "caption": "DBS digibank — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/dbs/04.jpg",
        "caption": "DBS digibank — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/dbs/05.jpg",
        "caption": "DBS digibank — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/dbs/06.jpg",
        "caption": "DBS digibank — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "revolut": {
    "name": "Revolut — Mobile Finance",
    "seller": "Revolut Ltd",
    "source": "Apple App Store (GB)",
    "storeUrl": "https://apps.apple.com/gb/app/revolut-mobile-finance/id932493382?uo=4",
    "icon": "/audit/revolut/icon.png",
    "kind": "store",
    "rating": 4.86,
    "ratingCount": 1076226,
    "screens": [
      {
        "src": "/audit/revolut/01.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/revolut/02.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/revolut/03.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/revolut/04.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/revolut/05.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/revolut/06.jpg",
        "caption": "Revolut — Mobile Finance — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "nubank": {
    "name": "Nubank: Conta, Cartão e mais",
    "seller": "NU PAGAMENTOS S/A INSTITUICAO DE PAGAMENTO",
    "source": "Apple App Store (BR)",
    "storeUrl": "https://apps.apple.com/br/app/nubank-conta-cart%C3%A3o-e-mais/id814456780?uo=4",
    "icon": "/audit/nubank/icon.png",
    "kind": "store",
    "rating": 4.82,
    "ratingCount": 1632755,
    "screens": [
      {
        "src": "/audit/nubank/01.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/nubank/02.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/nubank/03.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/nubank/04.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/nubank/05.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/nubank/06.jpg",
        "caption": "Nubank: Conta, Cartão e mais — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "grab": {
    "name": "Grab: Food Delivery, Taxi Ride",
    "seller": "GRABTAXI HOLDINGS PTE. LTD.",
    "source": "Apple App Store (SG)",
    "storeUrl": "https://apps.apple.com/sg/app/grab-food-delivery-taxi-ride/id647268330?uo=4",
    "icon": "/audit/grab/icon.png",
    "kind": "store",
    "rating": 4.78,
    "ratingCount": 251323,
    "screens": [
      {
        "src": "/audit/grab/01.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/grab/02.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/grab/03.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/grab/04.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/grab/05.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/grab/06.jpg",
        "caption": "Grab: Food Delivery, Taxi Ride — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "claude": {
    "name": "Claude by Anthropic",
    "seller": "Anthropic PBC",
    "source": "Apple App Store (US)",
    "storeUrl": "https://apps.apple.com/us/app/claude-by-anthropic/id6473753684?uo=4",
    "icon": "/audit/claude/icon.png",
    "kind": "store",
    "rating": 4.72,
    "ratingCount": 263229,
    "screens": [
      {
        "src": "/audit/claude/01.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/claude/02.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/claude/03.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/claude/04.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/claude/05.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/claude/06.jpg",
        "caption": "Claude by Anthropic — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  },
  "chatgpt": {
    "name": "ChatGPT",
    "seller": "OpenAI OpCo, LLC",
    "source": "Apple App Store (US)",
    "storeUrl": "https://apps.apple.com/us/app/chatgpt/id6448311069?uo=4",
    "icon": "/audit/chatgpt/icon.png",
    "kind": "store",
    "rating": 4.83,
    "ratingCount": 10332633,
    "screens": [
      {
        "src": "/audit/chatgpt/01.jpg",
        "caption": "ChatGPT — App Store screenshot 1",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/chatgpt/02.jpg",
        "caption": "ChatGPT — App Store screenshot 2",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/chatgpt/03.jpg",
        "caption": "ChatGPT — App Store screenshot 3",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/chatgpt/04.jpg",
        "caption": "ChatGPT — App Store screenshot 4",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/chatgpt/05.jpg",
        "caption": "ChatGPT — App Store screenshot 5",
        "archetype": "Store creative"
      },
      {
        "src": "/audit/chatgpt/06.jpg",
        "caption": "ChatGPT — App Store screenshot 6",
        "archetype": "Store creative"
      }
    ]
  }
};
