/**
 * GENERATED by scripts/build-screen-matrix.mjs — do not hand-edit.
 *
 * Source: the SCBX Screen Estate artefact, a dated snapshot held outside the
 * repo. Re-run the generator when it is re-captured.
 *
 * Screens: 145 · Apps: 9 · Archetypes: 10
 * Archetype classification resolved: yes
 */

export interface MatrixScreen {
  src: string;
  app: string;
  appName: string;
  archetype: string;
  description: string;
}

export interface MatrixApp {
  slug: string;
  name: string;
  count: number;
}

export const matrixApps: MatrixApp[] = [
  {
    "slug": "scb-easy",
    "name": "SCB EASY",
    "count": 46
  },
  {
    "slug": "scbam-fund-click",
    "name": "SCBAM Fund Click",
    "count": 13
  },
  {
    "slug": "cardx",
    "name": "CardX",
    "count": 14
  },
  {
    "slug": "finnix",
    "name": "FINNIX",
    "count": 12
  },
  {
    "slug": "moneythunder",
    "name": "MoneyThunder",
    "count": 12
  },
  {
    "slug": "เง-นไชโย-ngern-chaiyo",
    "name": "เงินไชโย · Ngern Chaiyo",
    "count": 13
  },
  {
    "slug": "pointx",
    "name": "POINTX",
    "count": 13
  },
  {
    "slug": "invx",
    "name": "INVX",
    "count": 12
  },
  {
    "slug": "token-x",
    "name": "Token X",
    "count": 10
  }
];

export const matrixArchetypes: string[] = [
  "Accounts & portfolio",
  "Cross-app handoff",
  "Detail & confirmation",
  "Home",
  "Login & onboarding",
  "Marketing",
  "Products & apply",
  "Rewards & offers",
  "Services & support",
  "Transact & pay"
];

export const matrixScreens: MatrixScreen[] = [
  {
    "src": "/screens/scb-easy-01.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Home",
    "description": "Store creative of the home shortcut grid — Scan / My QR bar, tiles for family transfers, mobile top-up, transactions, Easy Pass and bills, then a promo carousel and a COVID-19 relief card."
  },
  {
    "src": "/screens/scb-easy-02.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Home",
    "description": "Same home creative, taller crop — also shows the five-item bottom bar and an Apply Loan & Credit Card row."
  },
  {
    "src": "/screens/scb-easy-03.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Home",
    "description": "Home dashboard: photo header, greeting, Scan / My QR bar, six service tiles, theme-store promotion, Easy Store strip, loan CTA, icon-only bottom bar"
  },
  {
    "src": "/screens/scbam-fund-click-01.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Home",
    "description": "Fund Click home — greeting row with cart and search, a purple promo carousel, fund-category tabs (recommended / popular / best return / e-class) and fund cards with YTD returns, then a market-summary strip and a five-tab bottom bar."
  },
  {
    "src": "/screens/scbam-fund-click-02.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Home",
    "description": "Fund Click home — greeting row with cart and search, a purple promo carousel, fund-category tabs (recommended / popular / best return / e-class) and fund cards with YTD returns, then a market-summary strip and a five-tab bottom bar."
  },
  {
    "src": "/screens/scbam-fund-click-03.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Home",
    "description": "Tablet rendering of the home screen — the same carousel and fund cards in a wider two-column layout."
  },
  {
    "src": "/screens/cardx-01.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Home",
    "description": "Card home: carousel of CardX VISA ····5789 with POINTX 531 and available credit 145,100.25, quick actions for instalment conversion, split payment and statement request, an application-status tile and an offers card."
  },
  {
    "src": "/screens/cardx-02.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Home",
    "description": "Card home: carousel of CardX VISA ····5789 with POINTX 531 and available credit 145,100.25, quick actions for instalment conversion, split payment and statement request, an application-status tile and an offers card."
  },
  {
    "src": "/screens/cardx-03.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Home",
    "description": "Home screen right edge: balance tile, pay-card and application-status shortcuts, a personalised offer card and a promotions carousel."
  },
  {
    "src": "/screens/finnix-01.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Home",
    "description": "FINNIX home — coin balance pill, a ฿250 bonus banner, an orange Nano FINNIX credit-line card showing ฿100,000.00 available, a request-higher-limit row and a Withdraw CTA over a two-tab bottom bar."
  },
  {
    "src": "/screens/finnix-02.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Home",
    "description": "FINNIX home — coin balance pill, a ฿250 bonus banner, an orange Nano FINNIX credit-line card showing ฿100,000.00 available, a request-higher-limit row and a Withdraw CTA over a two-tab bottom bar."
  },
  {
    "src": "/screens/moneythunder-01.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Home",
    "description": "Logged-in home — a hero card for 24-hour online lending with a browse-loans CTA, a three-icon quick-action row, a news carousel and a Bank of Thailand trust strip."
  },
  {
    "src": "/screens/moneythunder-02.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Home",
    "description": "Home, fuller crop — brand lockup, an offer card for a cash loan up to ฿1,000,000, four quick actions, a credit-tip banner and a four-tab bottom bar."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-01.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Home",
    "description": "App home — yellow header greeting with mascot avatar and a 1,000-point chip, an active car-loan card showing ฿1,800.00 due 1 Jan, then a loan-category carousel and a promo banner."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-02.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Home",
    "description": "App home — yellow header greeting with mascot avatar and a 1,000-point chip, an active car-loan card showing ฿1,800.00 due 1 Jan, then a loan-category carousel and a promo banner."
  },
  {
    "src": "/screens/pointx-01.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Home",
    "description": "PointX home — greeting, a 25,000 point balance chip, quick actions for partner points, cashback, airlines and coupons, a top-sellers carousel and a flash-deal rail with Baht + point pricing. Tab bar: Home / Shop / SCB EASY hub / X Store / My POINTX."
  },
  {
    "src": "/screens/pointx-02.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Home",
    "description": "PointX home — greeting, a 25,000 point balance chip, quick actions for partner points, cashback, airlines and coupons, a top-sellers carousel and a flash-deal rail with Baht + point pricing. Tab bar: Home / Shop / SCB EASY hub / X Store / My POINTX."
  },
  {
    "src": "/screens/pointx-03.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Home",
    "description": "PointX home — own navigation, colour and type; partner points, coupons, cashback, airlines, transfer"
  },
  {
    "src": "/screens/invx-01.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Home",
    "description": "INVX dark home — avatar with PLATINUM tier chip, a points promo card, a purple portfolio card showing ฿1,789,487,320 and +1.24%, a price-change row and a deposit nudge."
  },
  {
    "src": "/screens/invx-02.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Home",
    "description": "INVX dark home — avatar with PLATINUM tier chip, a points promo card, a purple portfolio card showing ฿1,789,487,320 and +1.24%, a price-change row and a deposit nudge."
  },
  {
    "src": "/screens/token-x-01.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Home",
    "description": "Home — avatar and Thai greeting, three circular quick actions for tokens, orders and wallet, then an editorial card and a utility-token card."
  },
  {
    "src": "/screens/token-x-02.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Home",
    "description": "Home — avatar and Thai greeting, three circular quick actions for tokens, orders and wallet, then an editorial card and a utility-token card."
  },
  {
    "src": "/screens/scb-easy-04.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Just4U spending insight — savings and credit-card tabs, a donut of April spend 32,655.45 with category breakdown and a View monthly spending button."
  },
  {
    "src": "/screens/scb-easy-05.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Just4U spending insight — savings and credit-card tabs, a donut of April spend 32,655.45 with category breakdown and a View monthly spending button."
  },
  {
    "src": "/screens/scb-easy-06.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Account summary — deposits and shops, each section a one-card carousel with a pager dot"
  },
  {
    "src": "/screens/scb-easy-07.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Account summary scrolled — cards, revolving loans and insurances"
  },
  {
    "src": "/screens/scb-easy-08.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "My deposits — balance right-aligned and unlabelled, More services dropdown pill"
  },
  {
    "src": "/screens/scb-easy-09.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "My deposits — account details expanded"
  },
  {
    "src": "/screens/scb-easy-10.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Transaction history — uncategorised rows, free-text notes"
  },
  {
    "src": "/screens/scb-easy-11.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Transaction period filter"
  },
  {
    "src": "/screens/scb-easy-12.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Accounts & portfolio",
    "description": "Credit card details"
  },
  {
    "src": "/screens/scbam-fund-click-04.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Accounts & portfolio",
    "description": "Portfolio — an e-class allowance card with a progress bar, four tabs, a donut allocation chart with a seven-row legend, and a holding card for SCBS&P500E."
  },
  {
    "src": "/screens/scbam-fund-click-05.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Accounts & portfolio",
    "description": "Portfolio — an e-class allowance card with a progress bar, four tabs, a donut allocation chart with a seven-row legend, and a holding card for SCBS&P500E."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-03.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Accounts & portfolio",
    "description": "Loan detail — a car-loan card marked not yet due with a ฿1,800.00 instalment and a Pay CTA, then a Chaiyo card showing ฿0.00 used against a ฿20,000.00 limit, with details and transactions tabs."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-04.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Accounts & portfolio",
    "description": "Loan detail — a car-loan card marked not yet due with a ฿1,800.00 instalment and a Pay CTA, then a Chaiyo card showing ฿0.00 used against a ฿20,000.00 limit, with details and transactions tabs."
  },
  {
    "src": "/screens/pointx-04.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Accounts & portfolio",
    "description": "My POINTX — balance card with history link, linked-card strip and an all-partners list (AIS, Amaze, Bangchak, blueplus+, J Point, MAX CARD) with balances and conversion rates."
  },
  {
    "src": "/screens/pointx-05.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Accounts & portfolio",
    "description": "My POINTX — balance card with history link, linked-card strip and an all-partners list (AIS, Amaze, Bangchak, blueplus+, J Point, MAX CARD) with balances and conversion rates."
  },
  {
    "src": "/screens/pointx-06.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Accounts & portfolio",
    "description": "PointX my points"
  },
  {
    "src": "/screens/invx-03.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Accounts & portfolio",
    "description": "Port Analytics — asset breakdown donut with a weight / P&L toggle and rows for bonds, stocks, structured notes, cash, intelligent port, digital assets and funds."
  },
  {
    "src": "/screens/invx-04.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Accounts & portfolio",
    "description": "Port Analytics — asset breakdown donut with a weight / P&L toggle and rows for bonds, stocks, structured notes, cash, intelligent port, digital assets and funds."
  },
  {
    "src": "/screens/token-x-03.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Accounts & portfolio",
    "description": "Wallet — total token value ฿265,000.00, a copyable wallet-address chip, three actions for transfer, receive and history, and a my-tokens list."
  },
  {
    "src": "/screens/token-x-04.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Accounts & portfolio",
    "description": "Wallet — total token value ฿265,000.00, a copyable wallet-address chip, three actions for transfer, receive and history, and a my-tokens list."
  },
  {
    "src": "/screens/scb-easy-13.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Personalised home with a quick-action grid (Transfer highlighted) over a wall of biller and partner logos."
  },
  {
    "src": "/screens/scb-easy-14.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Personalised home with a quick-action grid (Transfer highlighted) over a wall of biller and partner logos."
  },
  {
    "src": "/screens/scb-easy-15.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Cardless ATM withdrawal — account and card tabs, amount chips, a 100–30,000 range field with daily-limit helper text and a primary Verify details button."
  },
  {
    "src": "/screens/scb-easy-16.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Cardless ATM withdrawal — account and card tabs, amount chips, a 100–30,000 range field with daily-limit helper text and a primary Verify details button."
  },
  {
    "src": "/screens/scb-easy-17.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer — 11 favourites as identical letter avatars, source account carousel, 16 banks as coloured initial tokens"
  },
  {
    "src": "/screens/scb-easy-18.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer — destination bank picker"
  },
  {
    "src": "/screens/scb-easy-19.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer — PromptPay tab"
  },
  {
    "src": "/screens/scb-easy-20.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer — history tab"
  },
  {
    "src": "/screens/scb-easy-21.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer form — recipient and amount"
  },
  {
    "src": "/screens/scb-easy-22.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer form — amount entry keypad"
  },
  {
    "src": "/screens/scb-easy-23.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Transfer form — complete, ready to review"
  },
  {
    "src": "/screens/scb-easy-24.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Transact & pay",
    "description": "Set a schedule — once"
  },
  {
    "src": "/screens/scbam-fund-click-06.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Transact & pay",
    "description": "Buy order for SCBRMS&P500 — buy / sell / switch / DCA tabs, amount ฿12,000 against a ฿1,000 minimum, effective date, promotion code and a credit-card payment selector."
  },
  {
    "src": "/screens/scbam-fund-click-07.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Transact & pay",
    "description": "Buy order for SCBRMS&P500 — buy / sell / switch / DCA tabs, amount ฿12,000 against a ฿1,000 minimum, effective date, promotion code and a credit-card payment selector."
  },
  {
    "src": "/screens/cardx-04.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Transact & pay",
    "description": "Instalment conversion — a checkbox list of eligible purchases (Fuji ฿2,000 and ZARA ฿2,500 selected), running total ฿4,500 and a Next button."
  },
  {
    "src": "/screens/cardx-05.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Transact & pay",
    "description": "Instalment conversion — a checkbox list of eligible purchases (Fuji ฿2,000 and ZARA ฿2,500 selected), running total ฿4,500 and a Next button."
  },
  {
    "src": "/screens/cardx-06.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Transact & pay",
    "description": "Cash advance (\"ดีจัง\") — account chip strip, a 25% p.a. rate warning, amount chips with 15,000 selected, and a repayment-plan radio group."
  },
  {
    "src": "/screens/finnix-03.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Transact & pay",
    "description": "Loan repayment — minimum-pay / pay-any toggle, total due ฿10,271.23, editable amount, interest breakdown, principal rolled to the next bill, a coupon row and a Pay now CTA."
  },
  {
    "src": "/screens/finnix-04.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Transact & pay",
    "description": "Loan repayment — minimum-pay / pay-any toggle, total due ฿10,271.23, editable amount, interest breakdown, principal rolled to the next bill, a coupon row and a Pay now CTA."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-05.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Transact & pay",
    "description": "Payment — instalment 1 of 12, ฿1,800.00 due, and a payment-channel picker offering SCB Easy with no fee or QR / barcode where a fee may apply."
  },
  {
    "src": "/screens/pointx-07.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Transact & pay",
    "description": "Pay with points — a phone at a POS terminal with a QR and an all-points / partial-points toggle over an amount field; beneath it the Shop tab with category chips and a special-rate grid."
  },
  {
    "src": "/screens/pointx-08.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Transact & pay",
    "description": "Pay with points — a phone at a POS terminal with a QR and an all-points / partial-points toggle over an amount field; beneath it the Shop tab with category chips and a special-rate grid."
  },
  {
    "src": "/screens/invx-05.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Transact & pay",
    "description": "Trade — symbol search and price alert, asset-class tabs, recently viewed tiles, INVX Picks chips and a watchlist top-gainer card."
  },
  {
    "src": "/screens/invx-06.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Transact & pay",
    "description": "Trade — symbol search and price alert, asset-class tabs, recently viewed tiles, INVX Picks chips and a watchlist top-gainer card."
  },
  {
    "src": "/screens/scb-easy-25.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Products & apply",
    "description": "Open a deposit account without a branch — NDID, 7-Eleven and Boonterm verification logos over a 3×4 service grid with the open-account tile lifted."
  },
  {
    "src": "/screens/scb-easy-26.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Products & apply",
    "description": "Open a deposit account without a branch — NDID, 7-Eleven and Boonterm verification logos over a 3×4 service grid with the open-account tile lifted."
  },
  {
    "src": "/screens/scb-easy-27.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Products & apply",
    "description": "Apply for loans and credit cards — a two-column catalogue of Up lending, Speedy Loan, Speedy Cash and Credit card."
  },
  {
    "src": "/screens/scb-easy-28.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Products & apply",
    "description": "Apply for loans and credit cards — a two-column catalogue of Up lending, Speedy Loan, Speedy Cash and Credit card."
  },
  {
    "src": "/screens/cardx-07.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Products & apply",
    "description": "CardX ULTRA PLATINUM product page — card art, minimum income ฿15,000/month, a calculate-limit row and an Apply now CTA."
  },
  {
    "src": "/screens/cardx-08.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Products & apply",
    "description": "CardX ULTRA PLATINUM product page — card art, minimum income ฿15,000/month, a calculate-limit row and an Apply now CTA."
  },
  {
    "src": "/screens/finnix-05.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Products & apply",
    "description": "Withdraw — remaining limit ฿100,000, a stepper and slider from ฿2,000 to ฿100,000, instalment due-date picker, per-day interest rows and a disbursement-account selector offering an SCB account or PromptPay."
  },
  {
    "src": "/screens/finnix-06.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Products & apply",
    "description": "Withdraw — remaining limit ฿100,000, a stepper and slider from ฿2,000 to ฿100,000, instalment due-date picker, per-day interest rows and a disbursement-account selector offering an SCB account or PromptPay."
  },
  {
    "src": "/screens/moneythunder-03.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Products & apply",
    "description": "Application step — a green-ticked checklist of general info, mobile-phone data and bank statement, with nine Thai bank tiles as statement sources and a Continue button."
  },
  {
    "src": "/screens/moneythunder-04.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Products & apply",
    "description": "Application step — a green-ticked checklist of general info, mobile-phone data and bank statement, with nine Thai bank tiles as statement sources and a Continue button."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-06.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Products & apply",
    "description": "Asset valuation inside a car-loan application — dropdowns for brand, model, year and sub-model with an Evaluate button."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-07.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Products & apply",
    "description": "Asset valuation inside a car-loan application — dropdowns for brand, model, year and sub-model with an Evaluate button."
  },
  {
    "src": "/screens/invx-07.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Products & apply",
    "description": "Discover — Opportunities / Markets & News segmented control, INVX Picks with asset-class filter chips, SCB and AOT cards each with an upside figure and a \"Why?\" chip, then a trending chip cloud."
  },
  {
    "src": "/screens/invx-08.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Products & apply",
    "description": "Discover — Opportunities / Markets & News segmented control, INVX Picks with asset-class filter chips, SCB and AOT cards each with an upside figure and a \"Why?\" chip, then a trending chip cloud."
  },
  {
    "src": "/screens/token-x-05.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Products & apply",
    "description": "Token listing — a featured XYZ Investment Token carousel card with its subscription window, tabs for open, upcoming and past offerings, and an ABC Investment Token row priced at ฿20."
  },
  {
    "src": "/screens/token-x-06.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Products & apply",
    "description": "Token listing — a featured XYZ Investment Token carousel card with its subscription window, tabs for open, upcoming and past offerings, and an ABC Investment Token row priced at ฿20."
  },
  {
    "src": "/screens/scb-easy-29.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "Banking services — 15-cell grid, one cell disabled, no search"
  },
  {
    "src": "/screens/scb-easy-30.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "My deposits — more services bottom sheet"
  },
  {
    "src": "/screens/scb-easy-31.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "Service centre — six quick actions in a floating card over a dimmed home"
  },
  {
    "src": "/screens/scb-easy-32.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "All services — three tabs, two-column lists, the only search in the app"
  },
  {
    "src": "/screens/scb-easy-33.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "Notification list"
  },
  {
    "src": "/screens/scb-easy-34.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "More options menu"
  },
  {
    "src": "/screens/scb-easy-35.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "Calendar — scheduled transactions"
  },
  {
    "src": "/screens/scb-easy-36.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Services & support",
    "description": "Settings"
  },
  {
    "src": "/screens/cardx-09.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Services & support",
    "description": "Permanent credit-limit increase — income-type dropdown, monthly income field, calculate-limit button and a stepper across a 15,000–50,000 range."
  },
  {
    "src": "/screens/cardx-10.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Services & support",
    "description": "Permanent credit-limit increase — income-type dropdown, monthly income field, calculate-limit button and a stepper across a 15,000–50,000 range."
  },
  {
    "src": "/screens/cardx-11.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Services & support",
    "description": "Card controls for CardX BEYOND — credit-limit stepper at ฿150,000 across a 10,000–200,000 range, with a modal sheet for a daily spend cap and a Confirm button."
  },
  {
    "src": "/screens/moneythunder-05.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Services & support",
    "description": "A PDPA banner over an in-app support screen — 24-hour help illustration and a LINE contact chip."
  },
  {
    "src": "/screens/scb-easy-37.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Rewards & offers",
    "description": "Easy Bonus — coupon-code input, a received-bonus carousel (Starbucks × SCB Debit Mastercard) and an activities section."
  },
  {
    "src": "/screens/scb-easy-38.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Rewards & offers",
    "description": "Credit card points — 377 points, every action opens PointX"
  },
  {
    "src": "/screens/scb-easy-39.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Rewards & offers",
    "description": "Gift box — received"
  },
  {
    "src": "/screens/scbam-fund-click-08.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Rewards & offers",
    "description": "Points — a dark Platinum tier card showing 4,620 points with an expiry line, redeem / history tabs, and a grid of fund-unit redemption tiles with one greyed out."
  },
  {
    "src": "/screens/scbam-fund-click-09.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Rewards & offers",
    "description": "Points — a dark Platinum tier card showing 4,620 points with an expiry line, redeem / history tabs, and a grid of fund-unit redemption tiles with one greyed out."
  },
  {
    "src": "/screens/scbam-fund-click-10.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Rewards & offers",
    "description": "Tablet rendering of the Points screen — Platinum card and a 2×2 redemption grid."
  },
  {
    "src": "/screens/cardx-12.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Rewards & offers",
    "description": "Promotion detail — Swensen's e-discount coupon up to ฿80, eligibility for CardX and SCB cards, terms and a Register CTA."
  },
  {
    "src": "/screens/cardx-13.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Rewards & offers",
    "description": "Promotion detail — Swensen's e-discount coupon up to ฿80, eligibility for CardX and SCB cards, terms and a Register CTA."
  },
  {
    "src": "/screens/finnix-07.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Rewards & offers",
    "description": "Coin wallet — 555,555 coins with a history link, an earn-on-time-payment explainer, and two privilege cards for a temporary limit increase or an interest discount."
  },
  {
    "src": "/screens/finnix-08.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Rewards & offers",
    "description": "Coin wallet — 555,555 coins with a history link, an earn-on-time-payment explainer, and two privilege cards for a temporary limit increase or an interest discount."
  },
  {
    "src": "/screens/pointx-09.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Rewards & offers",
    "description": "PointX X Store"
  },
  {
    "src": "/screens/scb-easy-40.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Detail & confirmation",
    "description": "Review transfer — red icon and red body copy where a summary belongs"
  },
  {
    "src": "/screens/scb-easy-41.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Detail & confirmation",
    "description": "PIN authorisation"
  },
  {
    "src": "/screens/scb-easy-42.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Detail & confirmation",
    "description": "Transfer successful — slip with watermark, four forward actions"
  },
  {
    "src": "/screens/scb-easy-43.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Detail & confirmation",
    "description": "Transfer slip — QR and actions"
  },
  {
    "src": "/screens/moneythunder-06.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Detail & confirmation",
    "description": "Approval result — confetti, \"You are approved\", a ฿100,000 limit in green, 2.75%/month (33% p.a.), a nano-finance badge promising disbursement within 10 minutes, and a decline-offer secondary."
  },
  {
    "src": "/screens/moneythunder-07.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Detail & confirmation",
    "description": "Contract step — an approval overlay for ฿1,000,000 above a sign-contract screen with a document icon, a primary sign CTA and a contact-officer button."
  },
  {
    "src": "/screens/invx-09.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Detail & confirmation",
    "description": "Instrument detail for AMD — price and day range, volume and market cap, an INVX fundamental radar chart, and a green Buy / red Sell bar."
  },
  {
    "src": "/screens/invx-10.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Detail & confirmation",
    "description": "Instrument detail for AMD — price and day range, volume and market cap, an INVX fundamental radar chart, and a green Buy / red Sell bar."
  },
  {
    "src": "/screens/scb-easy-44.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Login & onboarding",
    "description": "PIN entry with biometric prompt"
  },
  {
    "src": "/screens/moneythunder-08.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Login & onboarding",
    "description": "An onboarding carousel slide (3 of 4) with back / next navigation and three bullets on application steps, withdrawal questions and offers."
  },
  {
    "src": "/screens/scb-easy-45.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Cross-app handoff",
    "description": "Partner app handoff interstitial — full screen, one button, no cancel"
  },
  {
    "src": "/screens/scb-easy-46.jpg",
    "app": "scb-easy",
    "appName": "SCB EASY",
    "archetype": "Marketing",
    "description": "Lock-screen push notification for a ฿300.00 credit. No app UI."
  },
  {
    "src": "/screens/scbam-fund-click-11.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Marketing",
    "description": "Purple key art — a phone showing only the Fund Click logo, with claims of free fees, a ฿1 minimum and global assets. play-06 is the tablet rendering."
  },
  {
    "src": "/screens/scbam-fund-click-12.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Marketing",
    "description": "Purple key art — a phone showing only the Fund Click logo, with claims of free fees, a ฿1 minimum and global assets. play-06 is the tablet rendering."
  },
  {
    "src": "/screens/scbam-fund-click-13.jpg",
    "app": "scbam-fund-click",
    "appName": "SCBAM Fund Click",
    "archetype": "Marketing",
    "description": "Purple key art — a phone showing only the Fund Click logo, with claims of free fees, a ฿1 minimum and global assets. play-06 is the tablet rendering."
  },
  {
    "src": "/screens/cardx-14.jpg",
    "app": "cardx",
    "appName": "CardX",
    "archetype": "Marketing",
    "description": "Brand cover — CardX wordmark and Thai positioning as a core SCBX business. Only slivers of a home feed visible."
  },
  {
    "src": "/screens/finnix-09.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Marketing",
    "description": "Hero — a hand holding a phone showing the FINNIX splash, street-vendor setting, headline \"alongside life's fighters\"."
  },
  {
    "src": "/screens/finnix-10.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Marketing",
    "description": "Hero — a hand holding a phone showing the FINNIX splash, street-vendor setting, headline \"alongside life's fighters\"."
  },
  {
    "src": "/screens/finnix-11.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Marketing",
    "description": "Vendor with the orange phoenix mascot — approval in 5 seconds, self-apply in app."
  },
  {
    "src": "/screens/finnix-12.jpg",
    "app": "finnix",
    "appName": "FINNIX",
    "archetype": "Marketing",
    "description": "Vendor with the orange phoenix mascot — approval in 5 seconds, self-apply in app."
  },
  {
    "src": "/screens/moneythunder-09.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Marketing",
    "description": "Model plus a 24-hour in-app application claim and a downloads badge. The tilted phone is unreadable as UI."
  },
  {
    "src": "/screens/moneythunder-10.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Marketing",
    "description": "Model plus a 24-hour in-app application claim and a downloads badge. The tilted phone is unreadable as UI."
  },
  {
    "src": "/screens/moneythunder-11.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Marketing",
    "description": "Splash — MoneyThunder logo with the ABACUS digital and SCBX endorsement and the Bank of Thailand line."
  },
  {
    "src": "/screens/moneythunder-12.jpg",
    "app": "moneythunder",
    "appName": "MoneyThunder",
    "archetype": "Marketing",
    "description": "Splash — MoneyThunder logo with the ABACUS digital and SCBX endorsement and the Bank of Thailand line."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-08.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Yellow sunburst hero with a 3D horse mascot in a straw hat."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-09.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Yellow sunburst hero with a 3D horse mascot in a straw hat."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-10.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Easy to apply with service to your door — a yellow card with a giant \"123\" and approval within 30 minutes."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-11.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Easy to apply with service to your door — a yellow card with a giant \"123\" and approval within 30 minutes."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-12.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Mascot mid-leap among floating cash — fast approval, fast cash."
  },
  {
    "src": "/screens/เง-นไชโย-ngern-chaiyo-13.jpg",
    "app": "เง-นไชโย-ngern-chaiyo",
    "appName": "เงินไชโย · Ngern Chaiyo",
    "archetype": "Marketing",
    "description": "Mascot mid-leap among floating cash — fast approval, fast cash."
  },
  {
    "src": "/screens/pointx-10.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Marketing",
    "description": "Welcome creative — POINTX wordmark, a model holding a phone showing only the splash, and 3D X-coins."
  },
  {
    "src": "/screens/pointx-11.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Marketing",
    "description": "Welcome creative — POINTX wordmark, a model holding a phone showing only the splash, and 3D X-coins."
  },
  {
    "src": "/screens/pointx-12.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Marketing",
    "description": "X Store rewards creative — floating reward cards for Shopee, iPhone, LINEMAN and Sony. Decorative, not legible UI."
  },
  {
    "src": "/screens/pointx-13.jpg",
    "app": "pointx",
    "appName": "POINTX",
    "archetype": "Marketing",
    "description": "X Store rewards creative — floating reward cards for Shopee, iPhone, LINEMAN and Sony. Decorative, not legible UI."
  },
  {
    "src": "/screens/invx-11.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Marketing",
    "description": "Brand plate — innovestX logo, \"Your Future, Empowered\", 3D coin render. The phone edge is too clipped to read."
  },
  {
    "src": "/screens/invx-12.jpg",
    "app": "invx",
    "appName": "INVX",
    "archetype": "Marketing",
    "description": "Brand plate — innovestX logo, \"Your Future, Empowered\", 3D coin render. The phone edge is too clipped to read."
  },
  {
    "src": "/screens/token-x-07.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Marketing",
    "description": "Dark navy brand plate — TOKEN X wordmark, \"A Subsidiary of SCBX Group\", two steeply tilted phones."
  },
  {
    "src": "/screens/token-x-08.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Marketing",
    "description": "Dark navy brand plate — TOKEN X wordmark, \"A Subsidiary of SCBX Group\", two steeply tilted phones."
  },
  {
    "src": "/screens/token-x-09.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Marketing",
    "description": "\"Be the first to invest in digital token\" over two phones lying almost flat; content rotated past legibility."
  },
  {
    "src": "/screens/token-x-10.jpg",
    "app": "token-x",
    "appName": "Token X",
    "archetype": "Marketing",
    "description": "\"Be the first to invest in digital token\" over two phones lying almost flat; content rotated past legibility."
  }
];
